remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  # - projects.md
  # - bookshelf.md
  
ignore:
  - README.md

footer: 'find me on <a href="https://orbistertius.substack.com">Substack</a> <a href="https://github.com/dawsoneliasen">Github</a> <a href="https://linkedin.com/in/dawsoneliasen">LinkedIn</a>'
