remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md
  - projects.md
  - bookshelf.md
  
ignore:
  - README.md

footer: 'connect with me on <a href="https://twitter.com/@dawsoneliasen">twitter</a> <a href="https://linkedin.com/in/dawsoneliasen">linkedin</a>'
